config/routes.rb
Rails.application.routes.draw do

  root 'shows#welcome'

  resources :shows, only: [:index, :show]
  resources :lists, only: [:index, :new, :create, :show]
  resources :episodes, only: [:show]
  resources :seasons, only: [:show]

  post 'lists/:id', to: 'lists#destroy'

  post 'vieweds/:id', to: 'vieweds#toggle_viewed'

  patch 'episodes/:id', to: 'episodes#update'


  patch 'seasons/:id', to: 'seasons#update'
  post 'seasons/:id', to: 'seasons#update'


  post 'shows/:id', to: 'shows#update'
  # patch 'shows/:id', to: 'shows#remove_from_queue'
  # post 'shows/:id', to: 'shows#add_to_queue'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

end

app/models/episode.rb
class Episode < ActiveRecord::Base
  belongs_to :season
  belongs_to :show
  has_many :vieweds


end

app/models/list.rb
class List < ActiveRecord::Base
  has_and_belongs_to_many  :shows
  has_many :vieweds

  # def time_left(show)
  #   @show = show
  #   @list = List.find(params[:id])
  #   episodes = @show.vieweds.where(list_id: @list.id)
  #   if episodes.where(viewed: true) == []
  #     0
  #   else
  #     (episodes.where(viewed: true).map(&:length).inject(:+) / 60.0).round(0)
  #   end
  # end

  def time_watched(show)

    if self.vieweds.where(viewed: true, show_id: show.id) == []
      0
    else
      (self.vieweds.where(viewed: true, show_id: show.id).map { |v| v.episode.length }.inject(:+) / 60.0).round(0)
    end
  end

  def time_left
    if self.vieweds == []
      0
    else
      (vieweds.where(viewed: false).map{|v| v.episode.length}.inject(:+) / 60.0 ).round(0)
    end
  end

  def has_show?(show)
    shows.include?(show)
  end

  def destroy_vieweds
    vieweds.destroy_all
  end
end

app/models/season.rb
class Season < ActiveRecord::Base
  belongs_to :show
  has_many :episodes, dependent: :destroy


end

app/models/show.rb
class Show < ActiveRecord::Base
  has_many :seasons, dependent: :destroy
  has_many :episodes
  has_many :vieweds
  has_and_belongs_to_many  :lists

  def runtime
    (self.episodes.map(&:length).inject(:+) / 60.0).round(0)
  end

  # def time_watched
  #   if self.vieweds.where(viewed: true) == []
  #     0
  #   else
  #     (self.vieweds.where(viewed: true).map { |v| v.episode.length }.inject(:+) / 60.0).round(0)
  #   end
  # end

  # def time_left
  #   self.runtime - self.time_watched
  # end
end

app/models/status.rb
class Status < ActiveRecord::Base
  belongs_to :list
  belongs_to :episode
end

app/models/viewed.rb
class Viewed < ActiveRecord::Base
  belongs_to :episode
  belongs_to :list
  belongs_to :show

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/episodes_controller.rb
class EpisodesController < ApplicationController

  def update
    @episode = Episode.find(params[:id])
    if @episode.watched == false
      @episode.watched = true
      @episode.save
      redirect_to(:back)
    else
      @episode.watched = false
      @episode.save
      redirect_to(:back)
    end
  end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)

    if @list.save
      flash[:success] = 'Queue successfully created.'
      redirect_to "/lists"
    else
      render :new
    end
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy_vieweds
    @list.destroy
    flash[:success] = 'List successfully destroyed.'
    redirect_to "/"
  end

private

  def list_params
    params.require(:list).permit(:name)
  end
end

app/controllers/seasons_controller.rb
class SeasonsController < ApplicationController

  def update
    @season = Season.find(params[:id])
    if @season.watched == true
      @season.watched = false

      @season.episodes.each do |episode|
        episode.watched = false
        episode.save
      end

      @season.save
      redirect_to(:back)
    else
      @season.watched = true
      @season.episodes.each do |episode|
        episode.watched = true
        episode.save
      end
      @season.save
      redirect_to(:back)
    end
  end

  # def toggle_watched
  #   @season = Season.find(params[:id])
  #   @user = @season.user
  #   @season.watched ? @season.unwatch : @season.watch
  # end
end

app/controllers/shows_controller.rb
class ShowsController < ApplicationController
  def welcome
    @shows = Show.all
  end

  def index
    @shows = Show.all
  end

# adds a show to a list and creates joins for each episode and list
  def update
    @show = Show.find(params[:id])
    @list = List.find(params[:list_id])

    if @show.lists.include?(@list)


      @list.vieweds.where(show_id: @show.id).destroy_all

      @show.lists.delete(@list)
      @show.save
      redirect_to(:back)
      flash[:success] = 'List successfully updated.'
    else
      @show.lists << @list
      @show.save
      @show.episodes.each do |episode|
        viewed = Viewed.create
        viewed.episode = episode
        viewed.list = @list
        viewed.show = @show
        viewed.save
      end
      redirect_to(:back)
      flash[:success] = 'List successfully updated.'
    end

  end

  def remove_from_queue
    @show = Show.find(params[:id])
    @list = List.find(params[:list_id])
      @list.vieweds.where(show_id: @show.id).destroy_all

      @show.lists.delete(@list)
      @show.save
      redirect_to(:back)
      flash[:success] = 'List successfully updated'

  end

  def add_to_queue

    @show = Show.find(params[:id])
    @list = List.find(params[:list_id])

    @show.lists << @list
    @show.save
    @show.episodes.each do |episode|
      viewed = Viewed.create
      viewed.episode = episode
      viewed.list = @list
      viewed.show = @show
      viewed.save
    end
    redirect_to(:back)
    flash[:success] = 'List successfully updated.'

  end

end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  def create
    @list = List.find(params[:list_id])
    @show = Show.find(params[:show_id])
    @episodes = @show.episodes

    if .save
      redirect_to
    else
      render
    end
  end

end

app/controllers/vieweds_controller.rb
# the name is Viewed because of problems with reserved words
# it is a join between episodes, shows and user lists that says whether or not an episode has been viewed by that user
class ViewedsController < ApplicationController

  def toggle_viewed
    @viewed = Viewed.find(params[:id])

    @viewed.viewed == true ? @viewed.viewed = false : @viewed.viewed = true
    @viewed.save
    redirect_to :back
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_flash.html.erb
<% flash.each do |key, message| %>
  <div class="<%= key %>">
    <%= message %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BingeWatchApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>
  <div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
      <a href="/" class="navbar-brand">BINGE-Y</a>
        <button type='button' class='navbar-toggle' data-toggle='collapse' data-target='.navbar-collapse'>
          <span class='icon-bar'></span>
          <span class='icon-bar'></span>
          <span class='icon-bar'></span>
        </button>
      </div>
         <ul class='nav navbar-nav navbar-right navbar-inverse collapse navbar-collapse'>
          <li><%= link_to "SHOWS", shows_path %></li>

          <li class="dropdown">
            <a href="#" data-toggle="dropdown" class="dropdown-toggle">QUEUES <b class="caret"></b></a>
              <ul class="dropdown-menu navbar-inverse">
                  <% List.all.each do |list| %>
                  <li><%= link_to list.name.upcase, list_path(list) %></li>
                  <% end %>

                  <li class="divider"></li>
                  <li><%= link_to "NEW QUEUE", new_list_path %></li>
              </ul>
          </li>

        </ul>
    </div>
  </div>

  <div class="buffer row"></div>
  <main>

  <%= yield %>
  </main>



  </div>
<h6><%= render 'flash' %></h6>

</body>

</html>

app/views/layouts/welcome.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BingeWatchApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>
  <div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
      <a href="/" class="navbar-brand">BINGE-Y</a>
        <button type='button' class='navbar-toggle' data-toggle='collapse' data-target='.navbar-collapse'>
          <span class='icon-bar'></span>
          <span class='icon-bar'></span>
          <span class='icon-bar'></span>
        </button>
      </div>

         <ul class='nav navbar-nav navbar-right collapse navbar-collapse'>
          <li>
            <div class="title_bar">
            <% if List.first.shows == [] %>
                <h2>FIND A SHOW TO BINGE!</h2>
            <% else %>
              <h2>YOU HAVE <%= List.first.shows.map(&:time_left).inject(:+) %> HOURS LEFT TO BINGE</h2>
            <% end %>
            </div>
           </li>
          <li><%= link_to "SHOWS", "/shows" %></li>
          <li><%= link_to "QUEUE", "lists/1" %></li>
        </ul>
    </div>
  </div>

  <div class="buffer row"></div>
  <main>

  <%= yield %>
  </main>


  </div>
</body>

</html>

app/views/lists/_form.html.erb
<%= form_for @list do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name%>
    <%= f.submit %>
<% end %>

app/views/lists/_showinfo.html.erb
<div class="show_text well">

<% if show.time_left > 0 %>
  <div class="binge_time">
    <h3 class="time_left"><%= show.time_left %> HOURS TO BINGE</h3> <%= render 'shows/addshow', :show => show %>
  </div>
  <p><%= show.description %></p>
<% else %>
  <h3 class="time_left">BINGING COMPLETE!</h3> <%= render 'shows/addshow', :show => show %>
  <p><%= show.description %></p>
<% end %>



  <ul class="collapsibleList list-unstyled">
    <% show.seasons.each do |season| %>
        <li>
          <label for="mylist-node <%= show.id %><%= season.number %>">
             <div class='season'><h4>Season <%= season.number %></h4></div>
             <%= render 'shows/changeseason', controller: "seasons",  :season => season %>
          </label>
          <input type="checkbox" id="mylist-node <%= show.id %><%= season.number %>" />
          <ul class="list-unstyled">
              <% season.episodes.sort.each do |episode| %>
              <li class="episode">
               <div class='ep_column'>Episode <%= episode.number %> </div>
               <% if episode.vieweds.viewed == false %>
                  <%= button_to "Mark as Watched", controller: "vieweds", action: "toggle_viewed", id: episode.vieweds.id %>
                <% else %>
                  <%= button_to "Mark as Unwatched", controller: "vieweds", action: "toggle_viewed", id: episode.vieweds.id %>
                <% end %>
              </li>
              <% end %>
            </ul>
        </li>
    <% end %>
  </ul>

</div>

app/views/lists/index.html.erb
<div id="fancy">
  <%= image_tag('bb.jpg', class: "img-responsive") %>
</div>
<section>
<% @lists.each do |list| %>

    <div class="artwork_small">
    <h2><%= link_to list.name.upcase, list_path(list) %></h2>

      <% if list.shows == [] %>
      <% else %>
      <%= render 'shows/artwork', :show => list.shows.first %>
      <% end %>
    </div>

<% end %>
</section>

app/views/lists/new.html.erb
<div class="container new_list">
  <section>
  <%= render 'form' %>
  </section>
</div>

app/views/lists/show.html.erb
<div class="container">
  <div class="title"><h1> <%= @list.name.upcase %> HAS <%= @list.time_left %> HOURS LEFT TO BINGE</h1></div>
  <% @list.shows.each do |show| %>
    <section class="tv_show">
        <div class='artwork'><%= render 'shows/artwork', :show => show %></div>


        <div class="show_text well">
          <div class="binge_time">
            <h3 class="time_left"><%= show.runtime - @list.time_watched(show)%> HOURS TO BINGE</h3>

    <%= button_to "Remove from #{@list.name.upcase}", controller: "shows", action: "update", list_id: @list.id, id: show.id %>
 </div>
         <p><%= show.description %></p>

          <ul class="collapsibleList list-unstyled">
            <% show.seasons.each do |season| %>
                <li>
                  <label for="mylist-node <%= show.id %><%= season.number %>">
                     <div class='season'><h4>Season <%= season.number %></h4></div>



                  </label>
                  <input type="checkbox" id="mylist-node <%= show.id %><%= season.number %>" />
                  <ul class="list-unstyled">
                    <% season.episodes.sort.each do |episode| %>
                      <li class="episode">
                       <div class='ep_column'>Episode <%= episode.number %> </div>
                        <% if episode.vieweds.where(list_id: @list.id).first.viewed == true %>
                          <%= button_to "Mark as Unwatched", controller: "vieweds", action: "toggle_viewed", id: episode.vieweds.where(list_id: @list.id).first.id %>
                        <% else %>
                          <%= button_to "Mark as Watched", controller: "vieweds", action: "toggle_viewed", id: episode.vieweds.where(list_id: @list.id).first.id %>
                        <% end %>

                      </li>
                    <% end %>
                    </ul>
                </li>
              <% end %>
          </ul>

        </div>
    </section>
  <% end %>
  <div class='add_remove'>    <%= button_to "DELETE QUEUE", controller: "lists", action: "destroy" %>
  </div>
</div>

app/views/shows/_addshow.html.erb
<% List.all.each do |list| %>
  <% if list.has_show?(show) %>
    <%= button_to "Remove from #{list.name.upcase}", controller: "shows", action: "update", list_id: list.id, id: show.id %>
  <% else %>
    <%= button_to "Add to #{list.name.upcase}", controller: "shows", action: "update", list_id: list.id, id: show.id %>
  <% end %>
<% end %>

app/views/shows/_artwork.html.erb
<div>
  <img class="img-responsive" src=<%= show.artwork %> alt=<%= show.name %>>
</div>

app/views/shows/_changeseason.html.erb
<% if season.episodes.all? { |ep| ep.watched == true } %>
  <%= button_to "Mark as Unwatched", controller: "seasons", action: "update", id: season.id %>
<% else %>
  <%= button_to "Mark as Watched", controller: "seasons", action: "update", id: season.id %>
<% end %>


viewed controller
  -toggle stuff
  -buttons to do so

# link_to @viewed.next_status @viewed.toggle
# "helper methods" (things that aren't actions/urls) need to be under private

app/views/shows/_checkbox.html.erb
<%= form_for show do |f| %>
  <%= f.label list.name %>
  <%= f.check_box :list_id %>
  <%= f.submit %>
<% end %>

app/views/shows/_form.html.erb
<%= form_for show do |f| %>
    <%= f.collection_select(:list_id, List.all, :id, :name) %>
    <%= f.submit :AddToQueue %>
<% end %>

app/views/shows/_showtext.html.erb
<div class="show_text well">


  <div class="binge_time">

    <h3 class="time_left"><%= show.runtime %> HOURS TO BINGE</h3><%= render 'shows/addshow', :show => show %>
  </div>
  <p><%= show.description %></p>





  <ul class="collapsibleList list-unstyled">
    <% show.seasons.each do |season| %>
        <li>
          <label for="mylist-node <%= show.id %><%= season.number %>">
             <div class='season'><h4>Season <%= season.number %></h4></div>
          </label>
          <input type="checkbox" id="mylist-node <%= show.id %><%= season.number %>" />
          <ul class="list-unstyled">
              <% season.episodes.sort.each do |episode| %>
              <li class="episode">
               <div class='ep_column'>Episode <%= episode.number %> </div>
              </li>
              <% end %>
            </ul>
        </li>
    <% end %>
  </ul>

</div>

app/views/shows/index.html.erb
<div class="container">
  <% @shows.sort.each do |show| %>
    <section class="tv_show">
        <div class="artwork"><%= render 'artwork', :show => show %></div>
        <%= render 'showtext', :show => show %>
    </section>
  <% end %>

</div>

app/views/shows/welcome.html.erb
<div id="fancy">
  <%= image_tag('bb.jpg', class: "img-responsive") %>
</div>
<section>
<% @shows.sort.each do |show| %>

    <div class="artwork_small">
      <%= render 'artwork', :show => show %>
      <div class="add_remove">
        <%= render 'shows/addshow', :show => show %>
      </div>
    </div>

<% end %>
</section>